language: ruby
before_install: gem install bundler -v '< 2'
bundler_args: --without metrics
script: "bundle exec rake spec_for_build"
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - 2.3.0
  - 2.4.3
  - 2.5.3
  - 2.6.0
  - rbx-3
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-head
